### ISSUE TITLE
change login from email to username

### ISSUE THREAD

**Issue by omnignorant** [MozillaHive/HiveCHI-rwm#117]
The login page prompts an email addy, change to prompt a username.

**Comment by omnignorant** [comment]
Hey @bteng22, just wondering where this landed? Are you still in progress? NOTE: we still want to collect people's email addresses at registration (for notifications, etc), but we don't need to use it for login.

**Comment by bteng22** [comment]
hey @omnignorant got it! This issue is still in progress since I'm still trying to get familiar with Rails again, but I'll double check with @dgliwa and see if we can hop on this together to knock it out. We'll let you know asap

**Comment by bteng22** [comment]
Just made a pull request for this issue actually! Feel free to merge it in if there aren't any problems.

**Comment by paul-k-me** [comment]
Hey @bteng22 , I actually recommend to allow user to log in with *either* username or email, in case people forget the email address: why restricting to just one or the other?!
I will leave the Pull Request open, so you can add more changes to the same branch, instead of committing the current change which removes the ability to log in by email.
@omnignorant , do you agree?

**Comment by jsub1** [comment]
@omnignorant @bteng22 The pull request has been accepted. I will take care of @paul-k-me 's request since I'm working in that file already.

**Comment by kyaroch** [comment]
Possible issue: currently usernames can contain special characters, so it's theoretically possible that one user's email address could be the same as another user's username, leaving one of them unable to use it to log in. But that's a weird corner case.
