### ISSUE TITLE
Trending info is currently fake

### ISSUE THREAD

**Issue by paul-k-me** [MozillaHive/HiveCHI-rwm#169]
In the Trending section of the dashboard, currently the information is based on fake data.  Build a query of the database based on actual attendance and/or on how many days out the various events are.

**Comment by kyaroch** [comment]
I added methods to find the n most popular upcoming events, either in general or by school. Currently the dashboard just displays the total number of attendees (since I think it looks better if it's not zero), but the methods for attendees by school are also there in the model, so feel free to use those later on.

I think the performance could be better - it's running too many database queries - but we can worry about that a bit later.
