### ISSUE TITLE
Query attendance table to persist data across sessions.

### ISSUE THREAD

**Issue by jsub1** [MozillaHive/HiveCHI-rwm#51]

**Comment by omnignorant** [comment]
Query the attendance table when populating the event search to hide events that are already in "my events" and when viewing events in "my events" so that attendance status to that event is visible to the user. 

For example, when viewing an event that has already been marked as attending, the "Join" buttons are  hidden and replaced with departure and transpo information: i.e. "you are walking departing early at 5:00pm" or "Pending response" in the case of a nudge.
